name: Code Quality

on: push

env:
  NODE_VERSION: 18

jobs:
  codeQuality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1.0.5

      - name: cargo-install
        uses: baptiste0928/cargo-install@v3.0.1

      - name: wasm-pack-action
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Build
        run: pnpm build

      - name: Check Quality
        run: pnpm quality
