name: Code Quality

on: push

env:
  NODE_VERSION: 18

jobs:
  codeQuality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable 18 months ago

      - name: wasm-pack-action
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Build
        run: pnpm build

      - name: Check Quality
        run: pnpm quality
